apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.21.2"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  values:
    monitoring:
      podMonitorEnabled: false
