apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma-production
  namespace: production
spec:
  interval: 10m
  chart:
    spec:
      chart: uptime-kuma
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    replicaCount: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
    persistence:
      enabled: true
      size: 5Gi
    externalDatabase:
      type: postgresql
      host: postgres-rw.production.svc
      port: 5432
      database: uptimekuma
      existingSecret: postgres-secret
    ingress:
      enabled: true
      hostname: uptime.local
      ingressClassName: nginx
      tls: true
      selfSigned: true
