apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma-staging
  namespace: staging
spec:
  interval: 10m
  chart:
    spec:
      chart: uptime-kuma
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    replicaCount: 1
    persistence:
      enabled: true
      size: 1Gi
    postgresql:
      enabled: false
    externalDatabase:
      type: postgresql
      host: postgres-rw.staging.svc
      port: 5432
      database: uptimekuma
      existingSecret: postgres-secret
    ingress:
      enabled: true
      hostname: uptime.staging.local
      ingressClassName: nginx
      tls: true
      selfSigned: true
